#!/bin/bash
echo '****************************************************************************'
echo '              download_wars.sh                                              '
echo '                      by zhanhaibin                                         '
echo '                           2017.10.10                                       '
echo '  说明：                                                                    '
echo '    1. 遍历ibas_deploy_order.txt文件。                                          '
echo '    2. 参数1，工作目录。                                                    '
echo '****************************************************************************'
# 设置参数变量
# 启动目录
STARTUP_FOLDER=`pwd`
# 工作目录默认第一个参数
WORK_FOLDER=$1
# 修正相对目录为启动目录
if [ "${WORK_FOLDER}" == "./" ]
then
  WORK_FOLDER=${STARTUP_FOLDER}
fi
# 未提供工作目录，则取启动目录
if [ "${WORK_FOLDER}" == "" ]
then
  WORK_FOLDER=${STARTUP_FOLDER}
fi
echo ${WORK_FOLDER}
#war包下载地址
IBAS_PACKAGES=ibas_packages
if [! -e ${IBAS_PACKAGES} ] then mkdir ${IBAS_PACKAGES} fi

#nexus3 地址
server=http://192.168.64.132:8081/repository
repo=maven-public



echo --工作的目录：${WORK_FOLDER}
# 获取下载模块
if [ ! -e ${WORK_FOLDER}/ibas_deploy_order.txt ]
then
  ls -l ${WORK_FOLDER} | awk '/^d/{print $NF}' > ${WORK_FOLDER}/ibas_deploy_order.txt
fi
# 遍历当前目录存
while read file
do
	echo 'download wars：'${file}
        # Maven artifact location
        name=${file}
        artifact=org/colorcoding/apps/$name
        path=$server/$repo/$artifact
        echo $path
        version=`curl -s "$path/maven-metadata.xml" | grep latest | sed "s/.*<latest>\([^<]*\)<\/latest>.*/\1/"`
        echo $version
        war=$name-$version.war
        url=$path/$version/$war
 
	# Download
	echo SURL: $url
	wget -q -N -O=${IBAC_PACKAGES} $url
 
	echo Done
done < ${WORK_FOLDER}/ibas_deploy_order.txt

